name: Copy to Repo Classifai Job
on:
  push:
    branches: main

jobs:
  build:
    name: Build Node.js
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Caching Dependencies
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build:normal

    # Commit the compiled codes in the cloud back into the repo
    - name: Auto-commit compiled codes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":package: Updated compiled codes"
        file_pattern: "dist/" # Only commit contents of dist folder / Similar to git add command

  copy:
    name: Copy job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Declaring output variable # Necessary to call PR's URL
        uses: kceb/pull-request-url-action@v1
        id: pr-url

      - name: Echo PR's URL # PR associated with merged commit
        run: echo "${{ steps.pr-url.outputs.url }}" 

      - name: Copy dist items into Repo Classifai
        uses: andstor/copycat-action@v3
        with:
          commit_message: ":lipstick: Compiled codes from ${{ steps.pr-url.outputs.url }}" # Commit message at repo classifai
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # Personal token to solve permission issue
          src_path: dist/classifai/. # Source to be copied
          dst_path: classifai-core/src/main/resources/webroot/. # Destination to be pasted
          dst_owner: CertifaiAI # Destination owner's name
          dst_repo_name: classifai # Destination repo's name
          src_branch: main # Source repo's branch
          dst_branch: faris_auto_pr # Destination repo's branch / It will create if branch not exist
          clean: true # Set to 'true' for emptying destination path prior pasting 
          
