name: Copy to Repo Classifai Job
on:
  push:
    branches: main

    paths:
      # Triggered when only this path has code changes during push
      - 'dist/classifai/**'

jobs:
  copy:
    name: Copy job
    runs-on: ubuntu-latest
    steps:
      - name: Declaring output variable # Necessary to call PR's URL
        uses: kceb/pull-request-url-action@v1
        id: pr-url

      - name: Echo PR's URL # PR associated with merged commit
        run: echo "${{ steps.pr-url.outputs.url }}" 

      - name: Copy dist items into Repo Classifai
        uses: andstor/copycat-action@v3
        with:
          commit_message: ":lipstick: Compiled codes from ${{ steps.pr-url.outputs.url }}" # Commit message at repo classifai
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # Personal token to solve permission issue
          src_path: dist/classifai/. # Source to be copied
          dst_path: classifai-core/src/main/resources/webroot/. # Destination to be pasted
          dst_owner: CertifaiAI # Destination owner's name
          dst_repo_name: classifai # Destination repo's name
          src_branch: main # Source repo's branch
          dst_branch: faris_auto_pr # Destination repo's branch / It will create if branch not exist
          clean: true # Set to 'true' for emptying destination path prior pasting 
          