name: Copy to Repo Classifai Job
on:
  push:
    branches: faris_added_copypaste_workflow

    paths:
      # Triggered when only this path has code changes during push
      - 'dist/classifai/**'

jobs:
  copy:
    name: Copy job
    runs-on: ubuntu-latest
    steps:
      - name: Declare some variables
        id: vars
        shell: bash
        run: | # Set output for branch name & short commit hash
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" 
          echo "##[set-output name=sha_short;]$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Copy dist items into Repo Classifai
        uses: andstor/copycat-action@v3
        with:
          commit_message: Update files from Repo Classifai_FrontEnd, branch ${{ steps.vars.outputs.branch }} at commit ${{ steps.vars.outputs.sha_short }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: dist/classifai/.
          dst_path: classifai-core/src/main/resources/webroot/.
          dst_owner: CertifaiAI
          dst_repo_name: classifai
          src_branch: main
          dst_branch: faris_auto_pr
          clean: false
           